export const SliderData4 = [
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/power-rack-row.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2021/10/single-arm-dumbbell-row.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2023/01/barbell-deadlift-front-view.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2023/06/close-grip-lat-pulldown-standard-bar-attachment.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/08/cable-seated-row.gif'
    }
  ];