export const SliderData3 = [
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/barbell-full-squat.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/03/bulgarian-split-spuat.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/09/atg-split-squat.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/11/dumbbell-glute-bridge.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2023/03/dumbbell-calf-raise.gif'
    }
  ];