export const SliderData = [
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/04/barbell-bench-press.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/05/incline-barbell-bench-press.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/10/resistance-band-push-ups.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2023/07/barbell-decline-bench-press.gif'
    },
    {
      image:
      'https://www.inspireusafoundation.org/wp-content/uploads/2022/07/pec-deck.gif'
    }
  ];